version: '3'
services:
  frontend:
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "5000:5000"  
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=auth
      - jwtSecret=covapp1
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
