# Stage 1: Build Node.js Backend
FROM node:14 as backend
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Stage 2: Production Image
FROM node:14
WORKDIR /app

# Copy built backend from Stage 1
COPY --from=backend /app /app

# Install PostgreSQL client
RUN apt-get update && apt-get install -y postgresql-client

# Expose port
EXPOSE 5000

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=root
ENV POSTGRES_HOST=localhost
ENV POSTGRES_PORT=5432
ENV POSTGRES_DB=auth
ENV jwtSecret=covapp1
# Run the backend server
CMD ["node", "index.js"]
